### ISSUE TITLE
Ambiguous method overloading

### ISSUE THREAD

**Issue by yoann-trouillet** [agorapulse/grails-aws-sdk-s3#1]
Hi,

just started using the modular AWS SDK plugin for Grails - Thanks for providing those for grails ! keep up the good work !

I am using

compile 'org.grails.plugins:aws-sdk-s3:2.0.0-beta6'

and getting this exception

org.quartz.JobExecutionException: groovy.lang.GroovyRuntimeException: Ambiguous method overloading for method com.amazonaws.services.s3.model.PutObjectRequest#<init>.
Cannot resolve which method to invoke for [class java.lang.String, class java.lang.String, null] due to overlapping prototypes between:
    [class java.lang.String, class java.lang.String, class java.lang.String]
    [class java.lang.String, class java.lang.String, class java.io.File]
    at grails.plugins.quartz.GrailsJobFactory$GrailsJob.execute(GrailsJobFactory.java:111)
    at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
    at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)

this is my call to the service is it's of any help .. 

amazonS3Service.storeFile("REPORTBUCKET", "s3FileName", excelFile, CannedAccessControlList.AuthenticatedRead)

Thanks for your help ..

**Comment by benorama** [comment]
Hi Yoann,

Looking at the exception trace, it looks like `excelFile` is `null` in your request? 
[class java.lang.String, class java.lang.String, _null_]

**Comment by yoann-trouillet** [comment]
Hi Benoit,

Yes I apologize. You are correct, I raised that issue way too quickly ! Sorry for wasting your time.

Thanks

**Comment by benorama** [comment]
No problem!
FYI, later this month, I'm going to release all the AWS SDK plugins (removed from beta status) and publish them to the official Grails3 plugins.
